### ISSUE TITLE
Support event tracking

### ISSUE THREAD

**Issue by deepu105** [yeoman/insight#42]
GA supports event tracking and IMO for yeoman generators this would make more sense than doing page tracking as running generator or sub generator is an event. https://developers.google.com/analytics/devguides/collection/analyticsjs/events#overview

**Comment by deepu105** [comment]
I would be willing to PR if you guys are interested

**Comment by SBoudrias** [comment]
PR is welcomed!

**Comment by deepu105** [comment]
OK ill give it a shot
