### ISSUE TITLE
When prompt times out, user is not opted-out

### ISSUE THREAD

**Issue by omefire** [yeoman/insight#46]
When the prompt times out, the user is not automatically opted-out because the optOut field doesn't get written to the config.json.
The issue is due to the fact that the 'this' used doesn't refer to the Insight Function Object:
https://github.com/yeoman/insight/blob/master/lib/index.js#L159

**Comment by SBoudrias** [comment]
As you found the bug and the cause, mind sending in a PR?

**Comment by omefire** [comment]
Thanks @SBoudrias . PR sent: https://github.com/yeoman/insight/pull/47

**Comment by omefire** [comment]
Thanks @SBoudrias for the merge. How long till this patch is released to NPM ?
I am relying on it for some work I need to get out as soon as possible.

**Comment by SBoudrias** [comment]
Done.

**Comment by omefire** [comment]
Awesome! Thanks!
