### ISSUE TITLE
yo error

### ISSUE THREAD

**Issue by rrkushner** [yeoman/insight#49]
========================================================================== (
vents.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read EINVAL
    at exports._errnoException (util.js:907:11)
    at TTY.onread (net.js:557:26)

I did:
npm install -g yo
npm install -g typings   and
npm i -g @microsoft/generator-sharepoint

Then, I get the error when I try 
yo @microsoft/sharepoint

**Comment by kevva** [comment]
Doesn't seem related to `yo`. Try opening an issue at the repo of the generator, or provide a better error message.
