### ISSUE TITLE
Configurable debounce value

### ISSUE THREAD

**Issue by rprieto** [yeoman/insight#58]
It looks like the save function is debounced to avoid making too many HTTP requests.

However, it also means there is an initial delay of 100ms between a call to `track('page')` and the request being sent. If the tool closes shortly after that (e.g. `process.exit`) then the tracking doesn't happen.

What do you think of an option to customise the debounce, for the cases where we care about the speed but are only making 1 or 2 requests (so there's nothing to debounce really).

```js
new Insight({
trackingCode: TRACKING_CODE,
debounce: 10,
pkg
})
```

**Comment by sindresorhus** [comment]
We can make the debounce leading so it never waits.

See: https://lodash.com/docs/#debounce

**Comment by rprieto** [comment]
Thanks for the very quick reply. Leading sounds perfect for my use case. Do you think it needs to be configurable to preserve the current behaviour?

**Comment by sindresorhus** [comment]
No, it doesn't need to be configurable.

**Comment by rprieto** [comment]
Just gave it a try locally, works perfectly when sending a single event! :100: However it's not quite enough when multiple calls are made back to back:

```js
insight.trackEvent('search', 'count', 'count', 58) // this call triggers the leading debounce
insight.trackEvent('search', 'pages', 'pages', 3)  // and this one falls in the 100ms window
```

In addition to `{leading: true}`, what about some mechanism to delay / collapse `_save()` to the end of the execution flow? I try the following code locally and it worked well.

```js
track () {
  // ...
  this._save()
}

trackEvent () {
  // ...
  this.save()
}

_save () {
  this._needSaving = true
  process.nextTick(() => this._saveBatch())
}

_saveBatch () {
  if (this._needSaving === false) return;
  this._needSaving = false
  // existing logic ...
  debounce(() => { /* ... */ }, 100, {leading: true})()
}
```

Ideally we'd check the queue length in the `_save` method, but it's only cleared when the debounce executes. This might not happen straight away, so we need another variable like `_needSaving` to keep track of whether we've already saved.

How does that sound?

**Comment by rprieto** [comment]
What can I do to help you integrate and release this change?
- The `leading: true` change looks trivial and would make a big difference.
- The second change is bigger (although still a few lines) and mostly helps with performance, avoiding many calls when `track` is called several times within the same run of the event loop.

**Comment by SBoudrias** [comment]
@rprieto send us a PR :) We'll be happy to get this change in!
