### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by sburnicki** [yeoman/insight#60]
Hi,

I would really love to see a new release of this package, so ther packages can upgrade.
The background is the version bump of `inquirer`. The old version referenced in 0.8.4 contains a bug that let's any application crash when using node 8 and not being used interactively, e.g. in a docker container.

As important projects like `cordova` depend on this, it really has a major impact on using these tools with node 8 in a docker container.

Thanks!

**Comment by SBoudrias** [comment]
Thanks for the report, I'll add this to my todos and prepare a new release soon.

**Comment by sburnicki** [comment]
Thanks!

**Comment by SBoudrias** [comment]
Done: 0.9.0 is out.
