### ISSUE TITLE
Regression in insight 0.10.2 which causes error in yo

### ISSUE THREAD

**Issue by mischah** [yeoman/insight#68]
Hej @SBoudrias, @raphinesse,

`v0.10.2` causes yo to crash. See yeoman/yo#613.

Any ideas about the reason for this?

btw. I wonder why there is no git tag for `v0.10.2` 🤔 
See https://github.com/yeoman/insight/releases.

**Comment by raphinesse** [comment]
Could you reproduce the error outside of Windows?

**Comment by mischah** [comment]
Yup.

**Comment by raphinesse** [comment]
Got it. On it.

**Comment by raphinesse** [comment]
See #69. For tagging and releasing I have to refer to @SBoudrias.

**Comment by raphinesse** [comment]
You should probably also double check [the line in `yo` that caused the error](https://github.com/yeoman/yo/blob/3fb6d2d3ffdb5f9a2a20c5fe9b67693a11582992/lib/cli.js#L198).

Wit the current implementation of `optOut`, this is equivalent to:
```js
insight.config.get('optOut') = insight.config.get('optOut');
```
Which, at least to me, has no apparent use aside from putting load on your disk.

**Comment by mischah** [comment]
Thank you very much for digging into that.

**Comment by raphinesse** [comment]
No problem. After all I was the one to break it. Sorry for the work caused.

**Comment by SBoudrias** [comment]
Thanks to you both for handling that issue quickly!
