### ISSUE TITLE
Any one could share insight roadmap ? (for macos monterey )

### ISSUE THREAD

**Issue by HillLiu** [yeoman/insight#78]
@sindresorhus or any admins:

When I deep a issue macos monterey can not run yo?

https://github.com/yeoman/yo/issues/683

I think YO as a scaffolds, it should run for most of people.

original I think it's a simple change, just need upgrade macos-release to 3.0.1, when macos-release 3.01 already support unknown version.

So the upgrade path should be -> insight -> os-name (v5.0.1) -> macos-release (3.0.1) .

The first problem os-name change to esm style, It also not a big problem just need change to async import, such as

```
(async ()=> {const {default: osname} = import("os-name");})();
```

The next one is big problem, xo.js alert "import() expressions are not supported yet."

I am not familiar with xo.js, when I try upgrade xo.js it look like a big changes.

So want to know does insight maintainer have any plan to upgrade it or you wish let community volunteered to have it.

Thanks
Hill

**Comment by gandarez** [comment]
Probably related to https://github.com/yeoman/yo/issues/683

**Comment by HillLiu** [comment]
@gandarez you're right, we're mention same ticket. 

You could go to  os-name and macos-release git repository to see
@sindresorhus already finish partial work, upgrade os-name (v5.0.1) -> macos-release (3.0.1).

https://github.com/sindresorhus/macos-release
https://github.com/sindresorhus/os-name

but not sure @sindresorhus if already have plan for yeoman/insight.

**Comment by HillLiu** [comment]
clean no update ticket.
